name: app
description: Double D Application

publish_to: 'none'

version: 0.1.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  carousel_slider: ^4.0.0
  url_launcher: ^6.0.20
  jwt_decode: ^0.3.1
  intl: ^0.17.0

  http: ^0.13.4
  
  # Firebase
  firebase_core: ^1.14.0      # 1.7.0
  cloud_firestore: ^3.1.11     # 2.5.3
  firebase_analytics: ^9.1.3  # 8.3.3
  firebase_messaging: ^11.2.12
  flutter_local_notifications: ^9.4.0
  flutter_app_badger: ^1.3.0

  # 사진 고를 때 사용
  image_picker: ^0.8.4+11
  image: ^3.1.3

  # State managemnet
  get: ^4.6.1

  # 토큰 정보 저장
  shared_preferences: ^2.0.13
  
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0



flutter:

  uses-material-design: true

  assets:
    - assets/image/
    - assets/font/
    - assets/icon/


  fonts:
    - family: NanumSR
      fonts:
        - asset: assets/font/nsr_r.ttf
        - asset: assets/font/nsr_l.ttf
          weight: 300
        - asset: assets/font/nsr_b.ttf
          weight: 700
        - asset: assets/font/nsr_eb.ttf
          weight: 900

